# -*- coding: utf-8 -*-
"""Hand_Writting_digit_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12JzXZQA9hilW_RnNd_VibiF1a7l4CP9j
"""

# import library
import numpy as np
import pandas as pd
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten

(X_train, y_train),(X_test,y_test)=mnist.load_data()

X_train

import matplotlib.pyplot as plt

# Select an image from the training set
image_index = 4  # You can change this index to view different images

# Display the image
plt.imshow(X_train[image_index], cmap="gray")
plt.title(f"Label: {y_train[image_index]}")
plt.show()

X_train.shape,X_test.shape,y_train.shape,y_test.shape

# normalize the binary value to modulus 255.0 as float
X_train = X_train / 255.0

X_train[[0]]

# Build the model
model = Sequential([
    Flatten(input_shape=(28, 28)),   # Flatten the 28x28 images to a 1D array
    Dense(128, activation='relu'),   # Dense layer with 128 units and ReLU activation
    Dropout(0.2),
    Dense(64, activation = 'relu'),
    Dropout(0.2),
    Dense(10, activation='softmax')  # Output layer with 10 units (one for each digit) and softmax activation
])
model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train,y_train, epochs=10, validation_data=(X_test,y_test))

# plor the training and validation accuacy over epochs 3
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# plor the training and validation accuacy over epochs 3
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# plor the training and validation accuacy over epochs 2
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

test_loss,test_acc = model.evaluate(X_test,y_test)

# prompt: Now i wanna  test the model

# Predict the labels for the test set
predicted_labels = model.predict(X_test)

# Get the index of the predicted label with the highest probability for each test image
predicted_labels = np.argmax(predicted_labels, axis=1)

# Check the predicted labels against the actual labels
correct_predictions = np.sum(predicted_labels == y_test)

# Calculate the accuracy of the model
accuracy = correct_predictions / len(y_test)

# Print the accuracy
print(f"Accuracy: {accuracy:.2f}")

# Select an image from the test set
image_index = 9 # You can change this index to view different images

# Display the image
plt.imshow(X_test[image_index], cmap="gray")
plt.title(f"Predicted Label: {predicted_labels[image_index]}, Actual Label: {y_test[image_index]}")
plt.show()