# -*- coding: utf-8 -*-
"""quora_dpl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOjNPboXB4gFO0IN3JTKvPMyfqpEbGSF
"""

import tensorflow as tf
import keras as krs
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,Conv1D,GlobalMaxPooling1D,Dense,LSTM,Bidirectional


from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

# load the dataset
data = pd.read_csv("/content/drive/MyDrive/Deep_learning_model/datasets/quora.csv")

data.sample(5)

data.info()

data.shape

data.describe()

# check null value
data.isnull().sum()

data.fillna(value=0,inplace=True)

data.isnull().any()

data.isnull().sum()

print(data['question1'].dtype)
print(data['question2'].dtype)

"""concate te columns after converting them to string"""

X = data["question1"].astype(str)+data["question2"].astype(str)
y = data['is_duplicate']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
X_seq = tokenizer.texts_to_sequences(X)
X_pad = pad_sequences(X_seq)

X_train, X_test, y_train, y_test = train_test_split(X_pad, y, test_size=0.2, random_state=42)

# prompt: what next

# Split the data into training and testing sets

# Define the model
model = tf.keras.Sequential([
    Embedding(len(tokenizer.word_index) + 1, 128, input_length=X_pad.shape[1]),
    Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the model
y_pred = model.predict(X_test)
y_pred = np.round(y_pred)
print(classification_report(y_test, y_pred))

# Create a confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=data['is_duplicate'].value_counts().index, yticklabels=data['is_duplicate'].value_counts().index)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Get the user input
question1 = input("Enter the first question: ")
question2 = input("Enter the second question: ")

# Tokenize the questions
question1_seq = tokenizer.texts_to_sequences([question1])
question2_seq = tokenizer.texts_to_sequences([question2])

# Pad the sequences
question1_pad = pad_sequences(question1_seq, maxlen=X_pad.shape[1])
question2_pad = pad_sequences(question2_seq, maxlen=X_pad.shape[1])

# Predict the answer
y_pred = model.predict([question1_pad, question2_pad])

# Print the result
if y_pred[0] > 0.5:
  print("The questions are duplicates.")
else:
  print("The questions are not duplicates.")

# prompt: bILSTM

model2 = tf.keras.Sequential([
    Embedding(len(tokenizer.word_index) + 1, 128, input_length=X_pad.shape[1]),
    Bidirectional(LSTM(64, return_sequences=True)),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model2.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the model
y_pred2 = model2.predict(X_test)
y_pred2 = np.round(y_pred2)
print(classification_report(y_test, y_pred2))

# Create a confusion matrix
cm2 = confusion_matrix(y_test, y_pred2)
sns.heatmap(cm2, annot=True, fmt='d', xticklabels=data['is_duplicate'].value_counts().index, yticklabels=data['is_duplicate'].value_counts().index)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Get the user input
question1 = input("Enter the first question: ")
question2 = input("Enter the second question: ")

# Tokenize the questions
question1_seq = tokenizer.texts_to_sequences([question1])
question2_seq = tokenizer.texts_to_sequences([question2])

# Pad the sequences
question1_pad = pad_sequences(question1_seq, maxlen=X_pad.shape[1])
question2_pad = pad_sequences(question2_seq, maxlen=X_pad.shape[1])

# Predict the answer
y_pred2 = model2.predict([question1_pad, question2_pad])

# Print the result
if y_pred2[0] > 0.5:
  print("The questions are duplicates.")
else:
  print("The questions are not duplicates.")

"""# BILSTM"""

model3 = tf.keras.Sequential([
    Embedding(len(tokenizer.word_index) + 1, 128, input_length=X_pad.shape[1]),
    Bidirectional(LSTM(64, return_sequences=True)),
    Bidirectional(LSTM(32)),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model3.fit(X_train, y_train, epochs=20, batch_size=32)

# Evaluate the model
y_pred3 = model3.predict(X_test)
y_pred3 = np.round(y_pred3)
print(classification_report(y_test, y_pred3))

# Create a confusion matrix
cm3 = confusion_matrix(y_test, y_pred3)
sns.heatmap(cm3, annot=True, fmt='d', xticklabels=data['is_duplicate'].value_counts().index, yticklabels=data['is_duplicate'].value_counts().index)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# Get the user input
question1 = input("Enter the first question: ")
question2 = input("Enter the second question: ")

# Tokenize the questions
question1_seq = tokenizer.texts_to_sequences([question1])
question2_seq = tokenizer.texts_to_sequences([question2])

# Pad the sequences
question1_pad = pad_sequences(question1_seq, maxlen=X_pad.shape[1])
question2_pad = pad_sequences(question2_seq, maxlen=X_pad.shape[1])

# Predict the answer
y_pred3 = model3.predict([question1_pad, question2_pad])

# Print the result
if y_pred3[0] > 0.5:
  print("The questions are duplicates.")
else:
  print("The questions are not duplicates.")





















